import type { ComparisonMode, ModeConfig } from '../types';

export const MODES: ModeConfig[] = [
  {
    id: 'model-vs-model',
    label: 'Model vs Model',
    emoji: '🤖',
    tagline: 'Score agreement between two LLM outputs',
    description: 'Benchmark how consistently two models respond to the same prompt — detect divergence before it reaches production.',
    text1Label: 'Model A Output',
    text2Label: 'Model B Output',
    text1Placeholder: 'Paste the output from Model A here…',
    text2Placeholder: 'Paste the output from Model B here…',
    interpret: (prob) => {
      if (prob >= 0.7)
        return {
          headline: 'Strong agreement',
          detail:
            'Both models produced substantially similar responses. Output variation is minimal.',
          color: 'green',
        };
      if (prob >= 0.4)
        return {
          headline: 'Partial agreement',
          detail:
            'Responses share some content but diverge on key points. Review differences carefully.',
          color: 'yellow',
        };
      return {
        headline: 'Significant divergence',
        detail:
          'Models produced substantially different responses. They likely disagree on the answer.',
        color: 'red',
      };
    },
  },
  {
    id: 'reference-vs-generated',
    label: 'Reference vs Generated',
    emoji: '📋',
    tagline: 'Evaluate answer quality against ground truth',
    description: 'Score faithfulness in real time — catch hallucinations and omissions before they reach users.',
    text1Label: 'Reference Answer',
    text2Label: 'Generated Answer',
    text1Placeholder: 'Paste the ground-truth / golden reference answer here…',
    text2Placeholder: 'Paste the generated or model-produced answer here…',
    interpret: (prob) => {
      if (prob >= 0.7)
        return {
          headline: 'High faithfulness',
          detail:
            'Generated answer closely matches the reference. Content is accurate and well-aligned.',
          color: 'green',
        };
      if (prob >= 0.4)
        return {
          headline: 'Moderate faithfulness',
          detail:
            'Partial alignment with the reference. Some correct content but notable gaps or deviations.',
          color: 'yellow',
        };
      return {
        headline: 'Low faithfulness',
        detail:
          'Generated answer deviates significantly from the reference. Quality may be insufficient.',
        color: 'red',
      };
    },
  },
  {
    id: 'context-vs-generated',
    label: 'Context vs Generated',
    emoji: '📚',
    tagline: 'Detect hallucinations against source context',
    description: 'Verify every claim in a generated answer is grounded in the retrieved context — RAG evaluation at inference speed.',
    text1Label: 'Source Context',
    text2Label: 'Generated Answer',
    text1Placeholder: 'Paste the source document or context provided to the model…',
    text2Placeholder: 'Paste the answer generated by the model…',
    interpret: (prob) => {
      if (prob >= 0.7)
        return {
          headline: 'Well-grounded',
          detail: 'Answer is well-supported by the context. Low hallucination risk.',
          color: 'green',
        };
      if (prob >= 0.4)
        return {
          headline: 'Partially grounded',
          detail:
            'Some claims are supported but content may extend beyond what the context provides.',
          color: 'yellow',
        };
      return {
        headline: 'Potential hallucination',
        detail:
          'Answer appears to contain content not supported by the provided context.',
        color: 'red',
      };
    },
  },
];

export const getModeConfig = (id: ComparisonMode): ModeConfig =>
  MODES.find((m) => m.id === id) ?? MODES[1];
