import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test, type Locator, type Page } from '@playwright/test';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const batchFixture = path.join(__dirname, 'fixtures', 'demo-batch.json');

const LONG_PAUSE = 1400;
const MEDIUM_PAUSE = 850;

async function pause(ms = MEDIUM_PAUSE) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function typeSlow(locator: Locator, value: string) {
  await locator.click();
  await locator.clear();
  await locator.pressSequentially(value, { delay: 18 });
}

async function preparePage(page: Page) {
  await page.addInitScript(() => {
    localStorage.clear();
  });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /SilverBullet/i })).toBeVisible();
  await pause();
}

test.describe('frontend long-form demo videos', () => {
  test.setTimeout(300_000);

  test('pair-analysis-demo', async ({ page }) => {
    await preparePage(page);

    await page.getByRole('button', { name: /Context vs Generated/i }).click();
    await pause();

    await page.getByRole('button', { name: /Signal Features/i }).click();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Signal Features/i }).click();
    await pause();

    await typeSlow(page.getByPlaceholder(/Label for Source Context/i), 'Policy context');
    await pause();
    await typeSlow(page.getByPlaceholder(/Label for Generated Answer/i), 'Assistant answer');
    await pause();

    await typeSlow(
      page.getByPlaceholder(/Paste the source document or context/i),
      'The source memo states that the Paris office has 120 seats today and a separate expansion is scheduled for next quarter.',
    );
    await pause();

    await typeSlow(
      page.getByPlaceholder(/Paste the answer generated by the model/i),
      'The assistant says the Paris office already has 200 seats and that the expansion finished last month.',
    );
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Analyse Pair/i }).click();
    await expect(page.getByText('Evaluation Score')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Drill Down/i }).click();
    await expect(page.getByText('Divergence Analysis')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);

    await typeSlow(page.getByPlaceholder('Experiment name'), 'Long inference pair demo');
    await pause();
    await typeSlow(page.getByPlaceholder('Notes (optional)'), 'Real inference demo with detailed drill-down opened for the recording.');
    await pause();
    await page.getByRole('button', { name: /Save Experiment/i }).click();
    await expect(page.getByText(/Saved to Experiments/i)).toBeVisible();
    await pause(LONG_PAUSE * 2);
  });

  test('batch-analysis-demo', async ({ page }) => {
    await preparePage(page);

    await page.getByRole('button', { name: /Model vs Model/i }).click();
    await pause();
    await typeSlow(page.getByPlaceholder(/e\.g\. GPT-4o/i).first(), 'GPT-4o');
    await pause();
    await page.getByRole('button', { name: /Set baseline/i }).first().click();
    await pause();
    await typeSlow(page.getByPlaceholder(/e\.g\. Claude 3\.5 Sonnet/i), 'Claude 3.5 Sonnet');
    await pause();

    await page.getByRole('button', { name: /Batch Eval/i }).click();
    await expect(page.getByText(/Upload JSON File/i)).toBeVisible();
    await pause();

    await page.getByRole('button', { name: /Example Test Cases/i }).click();
    await pause();
    await page.getByRole('button', { name: /Load Example/i }).first().click();
    await pause(LONG_PAUSE);

    await page.locator('input[type="file"]').setInputFiles(batchFixture);
    await expect(page.getByText(/3 pairs ready/i)).toBeVisible();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Analyse Batch \(3\)/i }).click();
    await expect(page.getByText(/Score Distribution/i)).toBeVisible({ timeout: 60_000 });
    await expect(page.getByText(/All Results/i)).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);

    await typeSlow(page.getByPlaceholder('Experiment name'), 'Long inference batch demo');
    await pause();
    await typeSlow(page.getByPlaceholder('Notes (optional)'), 'Real batch inference demo with baseline labels and charts visible.');
    await pause();
    await page.getByRole('button', { name: /Save Experiment/i }).click();
    await expect(page.getByText(/Saved to Experiments/i)).toBeVisible();
    await pause(LONG_PAUSE * 2);
  });

  test('experiments-rerun-demo', async ({ page }) => {
    await preparePage(page);

    await page.getByRole('button', { name: /Context vs Generated/i }).click();
    await pause();
    await page.getByRole('button', { name: /Example Test Cases/i }).click();
    await pause();
    await page.getByRole('button', { name: /Load Example/i }).nth(1).click();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Analyse Pair/i }).click();
    await expect(page.getByText('Evaluation Score')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE);

    await typeSlow(page.getByPlaceholder('Experiment name'), 'Long inference experiments demo');
    await pause();
    await typeSlow(page.getByPlaceholder('Notes (optional)'), 'Shows saved history, expanded card details, and a rerun with real inference.');
    await pause();
    await page.getByRole('button', { name: /Save Experiment/i }).click();
    await expect(page.getByText(/Saved to Experiments/i)).toBeVisible();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Experiments/i }).click();
    await expect(page.getByText(/Long inference experiments demo/i)).toBeVisible();
    await pause();

    await page.getByText(/Long inference experiments demo/i).click();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Edit/i }).click();
    await pause();
    await typeSlow(page.locator('textarea').last(), 'Shows saved history, expanded card details, and a rerun with real inference plus updated notes.');
    await pause();
    await page.getByRole('button', { name: /^Save$/i }).click();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Re-run/i }).click();
    await expect(page.getByRole('button', { name: /Analyse Pair/i })).toBeVisible();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Analyse Pair/i }).click();
    await expect(page.getByText('Evaluation Score')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Drill Down/i }).click();
    await expect(page.getByText('Divergence Analysis')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);
  });

  test('full-product-showcase-demo', async ({ page }) => {
    await preparePage(page);

    await page.getByRole('button', { name: /Signal Features/i }).click();
    await pause(LONG_PAUSE * 2);

    await page.getByRole('button', { name: /Model vs Model/i }).click();
    await pause();
    await typeSlow(page.getByPlaceholder(/e\.g\. GPT-4o/i).first(), 'GPT-4o');
    await pause();
    await page.getByRole('button', { name: /Set baseline/i }).first().click();
    await pause();
    await typeSlow(page.getByPlaceholder(/e\.g\. Claude 3\.5 Sonnet/i), 'Claude 3.5 Sonnet');
    await pause();
    await page.getByRole('button', { name: /Example Test Cases/i }).click();
    await pause();
    await page.getByRole('button', { name: /Load Example/i }).first().click();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Analyse Pair/i }).click();
    await expect(page.getByText('Evaluation Score')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);

    await page.getByRole('button', { name: /Drill Down/i }).click();
    await expect(page.getByText('Divergence Analysis')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);

    await typeSlow(page.getByPlaceholder('Experiment name'), 'Full showcase pair run');
    await pause();
    await typeSlow(page.getByPlaceholder('Notes (optional)'), 'Captures the pair workflow before moving into batch and experiments.');
    await pause();
    await page.getByRole('button', { name: /Save Experiment/i }).click();
    await expect(page.getByText(/Saved to Experiments/i)).toBeVisible();
    await pause(LONG_PAUSE);

    await page.getByRole('button', { name: /Batch Eval/i }).click();
    await expect(page.getByText(/Upload JSON File/i)).toBeVisible();
    await pause();
    await page.locator('input[type="file"]').setInputFiles(batchFixture);
    await expect(page.getByText(/3 pairs ready/i)).toBeVisible();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Analyse Batch \(3\)/i }).click();
    await expect(page.getByText(/Score Distribution/i)).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);

    await typeSlow(page.getByPlaceholder('Experiment name'), 'Full showcase batch run');
    await pause();
    await typeSlow(page.getByPlaceholder('Notes (optional)'), 'Adds charts and all-results table to the same long-form recording.');
    await pause();
    await page.getByRole('button', { name: /Save Experiment/i }).click();
    await expect(page.getByText(/Saved to Experiments/i)).toBeVisible();
    await pause(LONG_PAUSE);

    await page.locator('button').filter({ hasText: 'Experiments' }).last().click();
    await expect(page.getByText(/Full showcase pair run/i)).toBeVisible();
    await expect(page.getByText(/Full showcase batch run/i)).toBeVisible();
    await pause();
    await page.getByText(/Full showcase pair run/i).click();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Re-run/i }).click();
    await expect(page.getByRole('button', { name: /Analyse Pair/i })).toBeVisible();
    await pause(LONG_PAUSE);
    await page.getByRole('button', { name: /Analyse Pair/i }).click();
    await expect(page.getByText('Evaluation Score')).toBeVisible({ timeout: 60_000 });
    await pause(LONG_PAUSE * 2);
  });
});
